/**
 * @file target.h
 * @desc Target description for SAMD21
 * @author Samuel Dewan
 * @date 2020-08-29
 * Last Author:
 * Last Edited On:
 */

#ifndef target_h
#define target_h

/* Enable Micro Trace Buffer if defined */
#define ENABLE_MTB

#define DONT_USE_CMSIS_INIT
#include "cmsis/include/samd21.h"
#include "cmsis/include/compiler.h"

#define TARGET_STRING "SAMD21"

/**
 *  Number of milliseconds elapsed since system was reset
 */
extern volatile uint32_t millis;

#define MS_TO_MILLIS(x) (x)

/* Clocks */
#define SAMD21_CLK_MSK_48MHZ    GCLK_CLKCTRL_GEN_GCLK0  // DFLL48M
#define SAMD21_CLK_MSK_32KHZ    GCLK_CLKCTRL_GEN_GCLK1  // XOSC32K
#define SAMD21_CLK_MSK_8MHZ     GCLK_CLKCTRL_GEN_GCLK3  // OSC8M
#define SAMD21_CLK_MSK_8KHZ     GCLK_CLKCTRL_GEN_GCLK7  // OSCULP32K / 4

/**
 *  Enum that defines common names for SAM peripheral clock channels that can be
 *  used accross multiple targets.
 */
enum peripheral_generic_clock {
    PERPH_GCLK_DFLL48_REF = 0x00,
    PERPH_GCLK_DPLL_REF,
    PERPH_GCLK_DPLL_32K,
    PERPH_GCLK_WDT,
    PERPH_GCLK_RTC,
    PERPH_GCLK_EIC,
    PERPH_GCLK_USB,
    PERPH_GCLK_EVSYS_CHANNEL_0,
    PERPH_GCLK_EVSYS_CHANNEL_1,
    PERPH_GCLK_EVSYS_CHANNEL_2,
    PERPH_GCLK_EVSYS_CHANNEL_3,
    PERPH_GCLK_EVSYS_CHANNEL_4,
    PERPH_GCLK_EVSYS_CHANNEL_5,
    PERPH_GCLK_EVSYS_CHANNEL_6,
    PERPH_GCLK_EVSYS_CHANNEL_7,
    PERPH_GCLK_EVSYS_CHANNEL_8,
    PERPH_GCLK_EVSYS_CHANNEL_9,
    PERPH_GCLK_EVSYS_CHANNEL_10,
    PERPH_GCLK_EVSYS_CHANNEL_11,
    PERPH_GCLK_SERCOM0_CORE = 0x14,
    PERPH_GCLK_SERCOM1_CORE,
    PERPH_GCLK_SERCOM2_CORE,
    PERPH_GCLK_SERCOM3_CORE,
    PERPH_GCLK_SERCOM4_CORE,
    PERPH_GCLK_SERCOM5_CORE,
    PERPH_GCLK_TCC0_TCC1,
    PERPH_GCLK_TCC2_TC3,
    PERPH_GCLK_TC4_TC5,
    PERPH_GCLK_TC6_TC7,
    PERPH_GCLK_ADC,
    PERPH_GCLK_AC_DIG,
    PERPH_GCLK_AC_ANA,
    PERPH_GCLK_DAC,
    PERPH_GCLK_PTC,
    PERPH_GCLK_I2S0,
    PERPH_GCLK_I2S1,
    PERPH_GCLK_TCC3
};

#define PERPH_BUS_CLK_BUS_MASK  ((uint32_t)0xFF << 24)

#define PERPH_BUS_CLK_BUS_AHB   ((uint32_t)0 << 24)
#define PERPH_BUS_CLK_BUS_APBA  ((uint32_t)1 << 24)
#define PERPH_BUS_CLK_BUS_APBB  ((uint32_t)2 << 24)
#define PERPH_BUS_CLK_BUS_APBC  ((uint32_t)3 << 24)

#define PERPH_BUS_CLK_BUS(x)    (x & PERPH_BUS_CLK_BUS_MASK)
#define PERPH_BUS_CLK_BIT(x)    (x & ~PERPH_BUS_CLK_BUS_MASK)

enum peripheral_bus_clock {
    PERPH_BUS_CLK_HPB0_AHB = PERPH_BUS_CLK_BUS_AHB | PM_AHBMASK_HPB0_Pos,
    PERPH_BUS_CLK_HPB1_AHB = PERPH_BUS_CLK_BUS_AHB | PM_AHBMASK_HPB1_Pos,
    PERPH_BUS_CLK_HPB2_AHB = PERPH_BUS_CLK_BUS_AHB | PM_AHBMASK_HPB2_Pos,
    PERPH_BUS_CLK_DSU_AHB = PERPH_BUS_CLK_BUS_AHB | PM_AHBMASK_DSU_Pos,
    PERPH_BUS_CLK_NVMCTRL_AHB = PERPH_BUS_CLK_BUS_AHB | PM_AHBMASK_NVMCTRL_Pos,
    PERPH_BUS_CLK_DMAC_AHB = PERPH_BUS_CLK_BUS_AHB | PM_AHBMASK_DMAC_Pos,
    PERPH_BUS_CLK_USB_AHB = PERPH_BUS_CLK_BUS_AHB | PM_AHBMASK_USB_Pos,

    PERPH_BUS_CLK_PAC0_APB = PERPH_BUS_CLK_BUS_APBA | PM_APBAMASK_PAC0_Pos,
    PERPH_BUS_CLK_PM_APB = PERPH_BUS_CLK_BUS_APBA | PM_APBAMASK_PM_Pos,
    PERPH_BUS_CLK_SYSCTRL_APB = PERPH_BUS_CLK_BUS_APBA | PM_APBAMASK_SYSCTRL_Pos,
    PERPH_BUS_CLK_GCLK_APB = PERPH_BUS_CLK_BUS_APBA | PM_APBAMASK_GCLK_Pos,
    PERPH_BUS_CLK_WDT_APB = PERPH_BUS_CLK_BUS_APBA | PM_APBAMASK_WDT_Pos,
    PERPH_BUS_CLK_RTC_APB = PERPH_BUS_CLK_BUS_APBA | PM_APBAMASK_RTC_Pos,
    PERPH_BUS_CLK_EIC_APB = PERPH_BUS_CLK_BUS_APBA | PM_APBAMASK_EIC_Pos,

    PERPH_BUS_CLK_PAC1_APB = PERPH_BUS_CLK_BUS_APBB | PM_APBBMASK_PAC1_Pos,
    PERPH_BUS_CLK_DSU_APB = PERPH_BUS_CLK_BUS_APBB | PM_APBBMASK_DSU_Pos,
    PERPH_BUS_CLK_NVMCTRL_APB = PERPH_BUS_CLK_BUS_APBB | PM_APBBMASK_NVMCTRL_Pos,
    PERPH_BUS_CLK_DMAC_APB = PERPH_BUS_CLK_BUS_APBB | PM_APBBMASK_DMAC_Pos,
    PERPH_BUS_CLK_USB_APB = PERPH_BUS_CLK_BUS_APBB | PM_APBBMASK_USB_Pos,
    PERPH_BUS_CLK_PORT_APB = PERPH_BUS_CLK_BUS_APBB | PM_APBBMASK_PORT_Pos,

    PERPH_BUS_CLK_PAC2_APB = PERPH_BUS_CLK_BUS_APBC | PM_APBCMASK_PAC2_Pos,
    PERPH_BUS_CLK_EVSYS_APB = PERPH_BUS_CLK_BUS_APBC | PM_APBCMASK_EVSYS_Pos,
    PERPH_BUS_CLK_SERCOM0_APB = PERPH_BUS_CLK_BUS_APBC | PM_APBCMASK_SERCOM0_Pos,
    PERPH_BUS_CLK_SERCOM1_APB = PERPH_BUS_CLK_BUS_APBC | PM_APBCMASK_SERCOM1_Pos,
    PERPH_BUS_CLK_SERCOM2_APB = PERPH_BUS_CLK_BUS_APBC | PM_APBCMASK_SERCOM2_Pos,
    PERPH_BUS_CLK_SERCOM3_APB = PERPH_BUS_CLK_BUS_APBC | PM_APBCMASK_SERCOM3_Pos,
    PERPH_BUS_CLK_SERCOM4_APB = PERPH_BUS_CLK_BUS_APBC | PM_APBCMASK_SERCOM4_Pos,
    PERPH_BUS_CLK_SERCOM5_APB = PERPH_BUS_CLK_BUS_APBC | PM_APBCMASK_SERCOM5_Pos,
    PERPH_BUS_CLK_TCC0_APB = PERPH_BUS_CLK_BUS_APBC | PM_APBCMASK_TCC0_Pos,
    PERPH_BUS_CLK_TCC1_APB = PERPH_BUS_CLK_BUS_APBC | PM_APBCMASK_TCC1_Pos,
    PERPH_BUS_CLK_TCC2_APB = PERPH_BUS_CLK_BUS_APBC | PM_APBCMASK_TCC2_Pos,
    PERPH_BUS_CLK_TC3_APB = PERPH_BUS_CLK_BUS_APBC | PM_APBCMASK_TC3_Pos,
    PERPH_BUS_CLK_TC4_APB = PERPH_BUS_CLK_BUS_APBC | PM_APBCMASK_TC4_Pos,
    PERPH_BUS_CLK_TC5_APB = PERPH_BUS_CLK_BUS_APBC | PM_APBCMASK_TC5_Pos,
    PERPH_BUS_CLK_TC6_APB = PERPH_BUS_CLK_BUS_APBC | PM_APBCMASK_TC6_Pos,
    PERPH_BUS_CLK_TC7_APB = PERPH_BUS_CLK_BUS_APBC | PM_APBCMASK_TC7_Pos,
    PERPH_BUS_CLK_ADC_APB = PERPH_BUS_CLK_BUS_APBC | PM_APBCMASK_ADC_Pos,
    PERPH_BUS_CLK_AC_APB = PERPH_BUS_CLK_BUS_APBC | PM_APBCMASK_AC_Pos,
    PERPH_BUS_CLK_DAC_APB = PERPH_BUS_CLK_BUS_APBC | PM_APBCMASK_DAC_Pos,
    PERPH_BUS_CLK_PTC_APB = PERPH_BUS_CLK_BUS_APBC | PM_APBCMASK_PTC_Pos,
    PERPH_BUS_CLK_I2S_APB = PERPH_BUS_CLK_BUS_APBC | PM_APBCMASK_I2S_Pos,
    PERPH_BUS_CLK_AC1_APB = PERPH_BUS_CLK_BUS_APBC | PM_APBCMASK_AC1_Pos
};

#endif /* target_h */
