SOURCE=circular-buffer
COMMON=common.c

TESTS = init_circular_buffer \
		circular_buffer_is_empty \
		circular_buffer_is_full \
		circular_buffer_unused \
		circular_buffer_capacity \
		circular_buffer_push \
		circular_buffer_try_push \
		circular_buffer_pop \
		circular_buffer_get_head \
		circular_buffer_move_head \
		circular_buffer_peak \
		circular_buffer_unpush \
		circular_buffer_has_char \
		circular_buffer_has_line \
		circular_buffer_clear

SRCDIR=../../src
include ../unittest.mk

