/**
 * @file target.h
 * @desc Target description for SAME54
 * @author Samuel Dewan
 * @date 2021-03-08
 * Last Author:
 * Last Edited On:
 */

#ifndef target_h
#define target_h

/* Enable Micro Trace Buffer if defined */
#define ENABLE_MTB

#define DONT_USE_CMSIS_INIT
#include "cmsis/include/same54.h"
#include "cmsis/include/compiler.h"

#define TARGET_STRING "SAME54"

/**
 *  Number of milliseconds elapsed since system was reset
 */
#define millis (RTC->MODE0.COUNT.reg)

#define MS_TO_MILLIS(x) ((((x) * 1024) + 500) / 1000)
#define MILLIS_TO_MS(x) ((((x) * 1000) + 512) / 1024)

/* Clocks */
#define ENABLE_XOSC0

#define SAME54_CLK_MSK_120MHZ   GCLK_PCHCTRL_GEN_GCLK0  // DPLL0
#define SAME54_CLK_MSK_48MHZ    GCLK_PCHCTRL_GEN_GCLK2  // DFLL48M
#define SAME54_CLK_MSK_32KHZ    GCLK_PCHCTRL_GEN_GCLK3  // XOSC32K
#define SAME54_CLK_MSK_12MHZ    GCLK_PCHCTRL_GEN_GCLK4  // XOSC0 or DFLL48M / 4
#define SAME54_CLK_MSK_100MHZ   GCLK_PCHCTRL_GEN_GCLK5  // DPLL1

/**
 *  Enum that defines common names for SAM peripheral clock channels that can be
 *  used accross multiple targets.
 */
enum peripheral_generic_clock {
    PERPH_GCLK_DFLL48_REF = 0,
    PERPH_GCLK_FDPLL0_REF,
    PERPH_GCLK_FDPLL1_REF,
    PERPH_GCLK_SLOW,
    PERPH_GCLK_EIC,
    PERPH_GCLK_FREQM_MSR,
    PERPH_GCLK_FREQM_REF,
    PERPH_GCLK_SERCOM0_CORE,
    PERPH_GCLK_SERCOM1_CORE,
    PERPH_GCLK_TC0_TC1,
    PERPH_GCLK_USB,
    PERPH_GCLK_EVSYS_CHANNEL_0,
    PERPH_GCLK_EVSYS_CHANNEL_1,
    PERPH_GCLK_EVSYS_CHANNEL_2,
    PERPH_GCLK_EVSYS_CHANNEL_3,
    PERPH_GCLK_EVSYS_CHANNEL_4,
    PERPH_GCLK_EVSYS_CHANNEL_5,
    PERPH_GCLK_EVSYS_CHANNEL_6,
    PERPH_GCLK_EVSYS_CHANNEL_7,
    PERPH_GCLK_EVSYS_CHANNEL_8,
    PERPH_GCLK_EVSYS_CHANNEL_9,
    PERPH_GCLK_EVSYS_CHANNEL_10,
    PERPH_GCLK_EVSYS_CHANNEL_11,
    PERPH_GCLK_SERCOM2_CORE,
    PERPH_GCLK_SERCOM3_CORE,
    PERPH_GCLK_TCC0_TCC1,
    PERPH_GCLK_TC2_TC3,
    PERPH_GCLK_CAN0,
    PERPH_GCLK_CAN1,
    PERPH_GCLK_TCC2_TCC3,
    PERPH_GCLK_TC4_TC5,
    PERPH_GCLK_PDEC,
    PERPH_GCLK_AC,
    PERPH_GCLK_CCL,
    PERPH_GCLK_SERCOM4_CORE,
    PERPH_GCLK_SERCOM5_CORE,
    PERPH_GCLK_SERCOM6_CORE,
    PERPH_GCLK_SERCOM7_CORE,
    PERPH_GCLK_TCC4,
    PERPH_GCLK_TC6_TC7,
    PERPH_GCLK_ADC0,
    PERPH_GCLK_ADC1,
    PERPH_GCLK_DAC,
    PERPH_GCLK_I2S0,
    PERPH_GCLK_I2S1,
    PERPH_GCLK_SDHC0,
    PERPH_GCLK_SDHC1,
    PERPH_GCLK_CM4_TRACE
};

#define PERPH_BUS_CLK_BUS_MASK  ((uint32_t)0xFF << 24)

#define PERPH_BUS_CLK_BUS_AHB   ((uint32_t)0 << 24)
#define PERPH_BUS_CLK_BUS_APBA  ((uint32_t)1 << 24)
#define PERPH_BUS_CLK_BUS_APBB  ((uint32_t)2 << 24)
#define PERPH_BUS_CLK_BUS_APBC  ((uint32_t)3 << 24)
#define PERPH_BUS_CLK_BUS_APBD  ((uint32_t)4 << 24)

#define PERPH_BUS_CLK_BUS(x)    (x & PERPH_BUS_CLK_BUS_MASK)
#define PERPH_BUS_CLK_BIT(x)    (x & ~PERPH_BUS_CLK_BUS_MASK)

enum peripheral_bus_clock {
    PERPH_BUS_CLK_HPB0_AHB = PERPH_BUS_CLK_BUS_AHB | MCLK_AHBMASK_HPB0_Pos,
    PERPH_BUS_CLK_HPB1_AHB = PERPH_BUS_CLK_BUS_AHB | MCLK_AHBMASK_HPB1_Pos,
    PERPH_BUS_CLK_HPB2_AHB = PERPH_BUS_CLK_BUS_AHB | MCLK_AHBMASK_HPB2_Pos,
    PERPH_BUS_CLK_HPB3_AHB = PERPH_BUS_CLK_BUS_AHB | MCLK_AHBMASK_HPB3_Pos,
    PERPH_BUS_CLK_DSU_AHB = PERPH_BUS_CLK_BUS_AHB | MCLK_AHBMASK_DSU_Pos,
    PERPH_BUS_CLK_NVMCTRL_AHB = PERPH_BUS_CLK_BUS_AHB | MCLK_AHBMASK_NVMCTRL_Pos,
    PERPH_BUS_CLK_CMCC_AHB = PERPH_BUS_CLK_BUS_AHB | MCLK_AHBMASK_CMCC_Pos,
    PERPH_BUS_CLK_DMAC_AHB = PERPH_BUS_CLK_BUS_AHB | MCLK_AHBMASK_DMAC_Pos,
    PERPH_BUS_CLK_USB_AHB = PERPH_BUS_CLK_BUS_AHB | MCLK_AHBMASK_USB_Pos,
    PERPH_BUS_CLK_PAC_AHB = PERPH_BUS_CLK_BUS_AHB | MCLK_AHBMASK_PAC_Pos,
    PERPH_BUS_CLK_QSPI_AHB = PERPH_BUS_CLK_BUS_AHB | MCLK_AHBMASK_QSPI_Pos,
    PERPH_BUS_CLK_GMAC_AHB = PERPH_BUS_CLK_BUS_AHB | MCLK_AHBMASK_GMAC_Pos,
    PERPH_BUS_CLK_SDHC0_AHB = PERPH_BUS_CLK_BUS_AHB | MCLK_AHBMASK_SDHC0_Pos,
    PERPH_BUS_CLK_SDHC1_AHB = PERPH_BUS_CLK_BUS_AHB | MCLK_AHBMASK_SDHC1_Pos,
    PERPH_BUS_CLK_CAN0_AHB = PERPH_BUS_CLK_BUS_AHB | MCLK_AHBMASK_CAN0_Pos,
    PERPH_BUS_CLK_CAN1_AHB = PERPH_BUS_CLK_BUS_AHB | MCLK_AHBMASK_CAN1_Pos,
    PERPH_BUS_CLK_ICM_AHB = PERPH_BUS_CLK_BUS_AHB | MCLK_AHBMASK_ICM_Pos,
    PERPH_BUS_CLK_PUKCC_AHB = PERPH_BUS_CLK_BUS_AHB | MCLK_AHBMASK_PUKCC_Pos,
    PERPH_BUS_CLK_QSPI2X_AHB = PERPH_BUS_CLK_BUS_AHB | MCLK_AHBMASK_QSPI_2X_Pos,
    PERPH_BUS_CLK_NVMCTRL_SMEEPROM_AHB = PERPH_BUS_CLK_BUS_AHB | MCLK_AHBMASK_NVMCTRL_SMEEPROM_Pos,
    PERPH_BUS_CLK_NVMCTRL_CACHE_AHB = PERPH_BUS_CLK_BUS_AHB | MCLK_AHBMASK_NVMCTRL_CACHE_Pos,

    PERPH_BUS_CLK_PAC_APB = PERPH_BUS_CLK_BUS_APBA | MCLK_APBAMASK_PAC_Pos,
    PERPH_BUS_CLK_PM_APB = PERPH_BUS_CLK_BUS_APBA | MCLK_APBAMASK_PM_Pos,
    PERPH_BUS_CLK_MCLK_APB = PERPH_BUS_CLK_BUS_APBA | MCLK_APBAMASK_MCLK_Pos,
    PERPH_BUS_CLK_RSTC_APB = PERPH_BUS_CLK_BUS_APBA | MCLK_APBAMASK_RSTC_Pos,
    PERPH_BUS_CLK_OSCCTRL_APB = PERPH_BUS_CLK_BUS_APBA | MCLK_APBAMASK_OSCCTRL_Pos,
    PERPH_BUS_CLK_OSC32KCTRL_APB = PERPH_BUS_CLK_BUS_APBA | MCLK_APBAMASK_OSC32KCTRL_Pos,
    PERPH_BUS_CLK_SUPC_APB = PERPH_BUS_CLK_BUS_APBA | MCLK_APBAMASK_SUPC_Pos,
    PERPH_BUS_CLK_GCLK_APB = PERPH_BUS_CLK_BUS_APBA | MCLK_APBAMASK_GCLK_Pos,
    PERPH_BUS_CLK_WDT_APB = PERPH_BUS_CLK_BUS_APBA | MCLK_APBAMASK_WDT_Pos,
    PERPH_BUS_CLK_RTC_APB = PERPH_BUS_CLK_BUS_APBA | MCLK_APBAMASK_RTC_Pos,
    PERPH_BUS_CLK_EIC_APB = PERPH_BUS_CLK_BUS_APBA | MCLK_APBAMASK_EIC_Pos,
    PERPH_BUS_CLK_FREQM_APB = PERPH_BUS_CLK_BUS_APBA | MCLK_APBAMASK_FREQM_Pos,
    PERPH_BUS_CLK_SERCOM0_APB = PERPH_BUS_CLK_BUS_APBA | MCLK_APBAMASK_SERCOM0_Pos,
    PERPH_BUS_CLK_SERCOM1_APB = PERPH_BUS_CLK_BUS_APBA | MCLK_APBAMASK_SERCOM1_Pos,
    PERPH_BUS_CLK_TC0_APB = PERPH_BUS_CLK_BUS_APBA | MCLK_APBAMASK_TC0_Pos,
    PERPH_BUS_CLK_TC1_APB = PERPH_BUS_CLK_BUS_APBA | MCLK_APBAMASK_TC1_Pos,

    PERPH_BUS_CLK_USB_APB = PERPH_BUS_CLK_BUS_APBB | MCLK_APBBMASK_USB_Pos,
    PERPH_BUS_CLK_DSU_APB = PERPH_BUS_CLK_BUS_APBB | MCLK_APBBMASK_DSU_Pos,
    PERPH_BUS_CLK_NVMCTRL_APB = PERPH_BUS_CLK_BUS_APBB | MCLK_APBBMASK_NVMCTRL_Pos,
    PERPH_BUS_CLK_PORT_APB = PERPH_BUS_CLK_BUS_APBB | MCLK_APBBMASK_PORT_Pos,
    PERPH_BUS_CLK_EVSYS_APB = PERPH_BUS_CLK_BUS_APBB | MCLK_APBBMASK_EVSYS_Pos,
    PERPH_BUS_CLK_SERCOM2_APB = PERPH_BUS_CLK_BUS_APBB | MCLK_APBBMASK_SERCOM2_Pos,
    PERPH_BUS_CLK_SERCOM3_APB = PERPH_BUS_CLK_BUS_APBB | MCLK_APBBMASK_SERCOM3_Pos,
    PERPH_BUS_CLK_TCC0_APB = PERPH_BUS_CLK_BUS_APBB | MCLK_APBBMASK_TCC0_Pos,
    PERPH_BUS_CLK_TCC1_APB = PERPH_BUS_CLK_BUS_APBB | MCLK_APBBMASK_TCC1_Pos,
    PERPH_BUS_CLK_TC2_APB = PERPH_BUS_CLK_BUS_APBB | MCLK_APBBMASK_TC2_Pos,
    PERPH_BUS_CLK_TC3_APB = PERPH_BUS_CLK_BUS_APBB | MCLK_APBBMASK_TC3_Pos,
    PERPH_BUS_CLK_RAMECC_APB = PERPH_BUS_CLK_BUS_APBB | MCLK_APBBMASK_RAMECC_Pos,

    PERPH_BUS_CLK_GMAC_APB = PERPH_BUS_CLK_BUS_APBC | MCLK_APBCMASK_GMAC_Pos,
    PERPH_BUS_CLK_TCC2_APB = PERPH_BUS_CLK_BUS_APBC | MCLK_APBCMASK_TCC2_Pos,
    PERPH_BUS_CLK_TCC3_APB = PERPH_BUS_CLK_BUS_APBC | MCLK_APBCMASK_TCC3_Pos,
    PERPH_BUS_CLK_TC4_APB = PERPH_BUS_CLK_BUS_APBC | MCLK_APBCMASK_TC4_Pos,
    PERPH_BUS_CLK_TC5_APB = PERPH_BUS_CLK_BUS_APBC | MCLK_APBCMASK_TC5_Pos,
    PERPH_BUS_CLK_PDEC_APB = PERPH_BUS_CLK_BUS_APBC | MCLK_APBCMASK_PDEC_Pos,
    PERPH_BUS_CLK_AC_APB = PERPH_BUS_CLK_BUS_APBC | MCLK_APBCMASK_AC_Pos,
    PERPH_BUS_CLK_AES_APB = PERPH_BUS_CLK_BUS_APBC | MCLK_APBCMASK_AES_Pos,
    PERPH_BUS_CLK_TRNG_APB = PERPH_BUS_CLK_BUS_APBC | MCLK_APBCMASK_TRNG_Pos,
    PERPH_BUS_CLK_ICM_APB = PERPH_BUS_CLK_BUS_APBC | MCLK_APBCMASK_ICM_Pos,
    PERPH_BUS_CLK_QSPI_APB = PERPH_BUS_CLK_BUS_APBC | MCLK_APBCMASK_QSPI_Pos,
    PERPH_BUS_CLK_CCL_APB = PERPH_BUS_CLK_BUS_APBC | MCLK_APBCMASK_CCL_Pos,

    PERPH_BUS_CLK_SERCOM4_APB = PERPH_BUS_CLK_BUS_APBD | MCLK_APBDMASK_SERCOM4_Pos,
    PERPH_BUS_CLK_SERCOM5_APB = PERPH_BUS_CLK_BUS_APBD | MCLK_APBDMASK_SERCOM5_Pos,
    PERPH_BUS_CLK_SERCOM6_APB = PERPH_BUS_CLK_BUS_APBD | MCLK_APBDMASK_SERCOM6_Pos,
    PERPH_BUS_CLK_SERCOM7_APB = PERPH_BUS_CLK_BUS_APBD | MCLK_APBDMASK_SERCOM7_Pos,
    PERPH_BUS_CLK_TCC4_APB = PERPH_BUS_CLK_BUS_APBD | MCLK_APBDMASK_TCC4_Pos,
    PERPH_BUS_CLK_TC6_APB = PERPH_BUS_CLK_BUS_APBD | MCLK_APBDMASK_TC6_Pos,
    PERPH_BUS_CLK_TC7_APB = PERPH_BUS_CLK_BUS_APBD | MCLK_APBDMASK_TC7_Pos,
    PERPH_BUS_CLK_ADC0_APB = PERPH_BUS_CLK_BUS_APBD | MCLK_APBDMASK_ADC0_Pos,
    PERPH_BUS_CLK_ADC1_APB = PERPH_BUS_CLK_BUS_APBD | MCLK_APBDMASK_ADC1_Pos,
    PERPH_BUS_CLK_DAC_APB = PERPH_BUS_CLK_BUS_APBD | MCLK_APBDMASK_DAC_Pos,
    PERPH_BUS_CLK_I2S_APB = PERPH_BUS_CLK_BUS_APBD | MCLK_APBDMASK_I2S_Pos,
    PERPH_BUS_CLK_PCC_APB = PERPH_BUS_CLK_BUS_APBD | MCLK_APBDMASK_PCC_Pos
};

#endif /* target_h */
