SOURCE=radio/rn2483

TESTS =	init_rn2483 \
		rn2483_service \
		cancel_receive \
		rn2483_send \
		rn2483_get_send_state \
		rn2483_clear_send_transaction \
		rn2483_receive \
		rn2483_receive_stop \
		rn2483_update_settings \
		rn2483_update_frequency_settings \
		rn2483_poll_gpio \
		rn2483_poll_gpio_in_progress \
		rn2483_set_pin_mode \
		rn2483_set_output \
		rn2483_toggle_output \
		rn2483_settings_set_freq \
		rn2483_settings_get_freq \
		rn2483_settings_set_rf \
		rn2483_settings_get_rf \
		rn2483_settings_set_sync \
		rn2483_settings_get_sync \
		rn2483_poll_gpio_pin \
		rn2483_poll_gpio_pin_in_progress \
		rn2483_get_pin_mode \
		rn2483_get_input \
		rn2483_get_analog

SRCDIR=../../src
include ../unittest.mk

